Register the Post Model to the admin site
Karthikeyantestpress/Blog_App pull request #2
Opened 2022-11-08 11:57 UTC by Karthikeyantestpress

2022-11-09 09:53 UTC, waranlogesh requested changes

2022-11-09 09:53 UTC, waranlogesh commented on mysite/blog/tests/test_admin.py
> +        self.assertEqual(test_superuser.username, "karthikeyanvenkat")
Same. Tests not needed

2022-11-09 09:53 UTC, waranlogesh commented on mysite/blog/tests/test_admin.py
> +        c = Client()
![image](https://user-images.githubusercontent.com/9105503/200798615-057d4a52-1a2d-435d-8cc9-54d6077cf8d9.png)

2022-11-09 09:53 UTC, waranlogesh commented on mysite/blog/tests/test_admin.py
> +        )
Use named arguments to be more explicit
```suggestion
        test_superuser = User.objects.create_superuser(
            username="karthikeyanvenkat", email="karthiktest51@gmail.com", password="123"
        )

```

2022-11-09 11:26 UTC, merged

2022-11-13 05:24 UTC, Karthikeyantestpress commented on mysite/blog/tests/test_admin.py
> +        )
Updated as the suggestion and Merged the PR