Support Pagination for the Websites
Karthikeyantestpress/Blog_App pull request #7
Opened 2022-11-09 06:02 UTC by Karthikeyantestpress

2022-11-09 10:08 UTC, waranlogesh requested changes

2022-11-09 10:08 UTC, waranlogesh commented on mysite/blog/views.py
> +    object_list = Post.published.all()
```suggestion
    published_posts = Post.published.all()
```

2022-11-09 10:08 UTC, waranlogesh commented on mysite/blog/views.py
> +    )
Multiple levels of abstraction violation
Extract the pagination logic to a helper function and use like this here `posts = paginate(queryset=posts, per_page=3)`

2022-11-09 10:09 UTC, waranlogesh commented
The title should be `Add pagination support in posts list`

2022-11-12 07:09 UTC, Karthikeyantestpress commented
New PR for this : https://github.com/Karthikeyantestpress/Blog_App/pull/13

2022-11-12 07:09 UTC, closed without merging